### ISSUE TITLE
Jakarta Data?

### ISSUE THREAD

**Issue by Tibor17** [eclipse-ee4j/jpa-api#334] opened 2021-11-21 01:10 UTC
We would like to see an annotation `@Repository` in the Jakarta project.
Pls adopt the feature implementation from Deltaspike Data or Spring Data.
Basically, the idea is the same in Deltaspike a Spring, the user develops an interface with repo methods either annotated with annotation `@Query` or the query is expressed by the name of abstract method in the interface.

The Jakarta EE can very hardly convince the cloud developers without adopting Data API and Microprofile API into Jakarta API.

**Comment by rhuan080** [comment] 2021-11-21 01:18
I agree!

I opened a discussion here about this topic in the past, and I like this
topic is coming back here. It is a useful pattern and widely used. With
this, I think it can be brought to the spec.

**Comment by m-reza-rahman** [comment] 2021-11-21 01:23
This is a duplicate of: https://github.com/eclipse-ee4j/jpa-api/issues/294. I suggest closing this issue and moving the discussion to the prior issue.

**Comment by rhuan080** [comment] 2021-11-21 01:27
Thank you Reza, for sharing this. I was searching here to share, but you
found. :-)

**Closed** 2021-11-21 02:00 UTC
